### ISSUE TITLE
간혹 오류나는 현상

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#8]
간혹 오류가 나면서 다운됩니다.
해당 오류내용입니다.

2019-01-21 11:08:18,796 - antsworker - INFO - actoin done
Traceback (most recent call last):
  File "./ants/ants.py", line 21, in <module>
    worker.start()
  File "D:\xampp\htdocs\bithumb\Ants-Auto-Trading-Bot-dev\ants\antsworker.py", line 53, in start
    mthList = email.mailSearch(M)
  File "D:\xampp\htdocs\bithumb\Ants-Auto-Trading-Bot-dev\ants\email_reader.py", line 88, in mailSearch
    rv, data = M.search(None, '(UNSEEN)')
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 723, in search
    typ, dat = self._simple_command(name, *criteria)
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 1019, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 1139, in _get_tagged_response
    self._get_response()
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 1047, in _get_response
    resp = self._get_line()
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 1149, in _get_line
    line = self.readline()
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\imaplib.py", line 310, in readline
    line = self.file.readline(_MAXLINE + 1)
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "c:\Users\user\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

**Comment by MuYoul** [comment]
imap 요청을 5초마다 한번씩 서버로 요청합니다. 아마도 너무 과하게 요구해서 서버측에서 연결을 끊어버린 것 같네요;

일단 예외 상황으로 처리하고 연결이 끊히면 지정된 시간후(5초) 다시 연결을 시도하도록 바꿔 두겠습니다.

연결이 자주 끊혔나요? 얼마나 자주 발생했는지 알고싶습니다.

**Comment by letsplayants** [comment]
넵 하루에 1번 정도 나온거 같습니다.
5초간격이면 그리 많은 건 아닌 것 같은데 네이버가 좀 야박하군요. ^^

**Comment by MuYoul** [comment]
음.. 그냥 간헐적으로 끊힌 것 같네요. 테스트할때 일부러 0초마다 메일을 읽어오도록 했는데 리젝을 안당하고 엄청 잘 읽어오네요;

일단 디펜스 코드는 작성해뒀는데, 테스트를 못해서 잘 동작하는지 걱정입니다. 이 부분은 테스트 케이스가 늘어가면서 차차 해결하도록 하죠

**Comment by letsplayants** [comment]
이 부분 오늘 업데이트로 해소된거 같은데 맞나요?

**Comment by MuYoul** [comment]
네. 다음에 같은 문제가 발생하면 다시 이슈로 등록하고 수정하도록 하겠습니다
