### ISSUE TITLE
간헐적으로 오류가 나오고 있습니다.

### ISSUE THREAD

**Issue by kimgun9631** [letsplayants/Ants-Auto-Trading-Bot#9]
이제 막 다운받아 설치하였습니다.
프로그램을 구동하고, 처음 이메일 얼러트를 받았는데 아래와 같은 오류가 나오고 있습니다.
확을을 부탁드립니다.

2019-01-21 19:11:16,331 - antsworker - INFO - doActoin :{'market': 'BTCKRW', 'time': '60M', 'action': 'SELL', 'exchange': 'BITHUMB'}
KeyError {'status': '5300', 'message': "Bad Request.(Request Time:reqTime1548065530617/nowTime1548065552260)'"}
Traceback (most recent call last):
  File "./ants/ants.py", line 21, in <module>
    worker.start()
  File "C:\Users\k\Desktop\자동매매\Ants-Auto-Trading-Bot-dev\ants\antsworker.py", line 60, in start
    doAction(ret)
  File "C:\Users\k\Desktop\자동매매\Ants-Auto-Trading-Bot-dev\ants\antsworker.py", line 93, in doAction
    sell(coinName)
  File "C:\Users\k\Desktop\자동매매\Ants-Auto-Trading-Bot-dev\ants\antsworker.py", line 130, in sell
    orderCnt = balance[0] - balance[1]  #코인 전량을 다 팔아버린다.
TypeError: 'NoneType' object is not subscriptable

**Comment by MuYoul** [comment]
음.. 이상하네요? 이런 오류는 나면 안되는 오류인데.. 오류가 얼마나 자주나는 지 알 수 있을까요?

해당 오류는 빗썸으로 오더를 넣는 도중에 발생하는 것으로 보입니다.  혹시 사용하시는 시스템이 너무 느릴 경우 오류가 자주 발생할 것으로 보입니다.

빗썸에서 잔고를 얻어와서 판매량을 결정하는 부분에서 잔고를 체크하는 부분이 서버측에서 리젝이 되는데 오류를 봤을 때 시스템이 너무 느려서 request time out이 발생하면서 서버측이 차단하는 것으로 예상됩니다.

조금 더 정확히 파악할 수 있도록 시스템 사양과 APIs키를 발급할 때 허용한 권한과 설정 파일을 올려주실 수 있을까요? 당연히 api key와 sercurity key는 삭제하시고 올리셔야해요!

**Comment by MuYoul** [comment]
아.. 오류코드 5300이네요 빗썸 API key 설정을 잘못하신것이네요 :)

빗썸 API Key 설정을 어떻게 했는지 볼 수 있을까요?
